export const PERMISSIONS = {
  PLATFORM_READ: 'platform:read',
  PLATFORM_UPDATE: 'platform:update',
  PLATFORM_DELETE: 'platform:delete',
  USERS_INVITE: 'users:invite',
  USERS_REMOVE: 'users:remove',
  USERS_LIST: 'users:list',
  ROLES_ASSIGN: 'roles:assign',
  ROLES_CREATE: 'roles:create',
  ROLES_DELETE: 'roles:delete',
  SCHEMAS_READ: 'schemas:read',
  SCHEMAS_WRITE: 'schemas:write',
  SCHEMAS_DELETE: 'schemas:delete',
  DOCS_READ: 'docs:read',
  DOCS_WRITE: 'docs:write',
  DOCS_DELETE: 'docs:delete',
  BLOBS_READ: 'blobs:read',
  BLOBS_UPLOAD: 'blobs:upload',
  BLOBS_DELETE: 'blobs:delete',
  TOKENS_DEPLOY: 'tokens:deploy',
  TOKENS_MINT: 'tokens:mint',
  NFTS_DEPLOY: 'nfts:deploy',
  NFTS_MINT: 'nfts:mint',
  EVENTS_CREATE: 'events:create',
  EVENTS_MINT: 'events:mint',
  REGISTRY_ANCHOR: 'registry:anchor',
  REGISTRY_DEPLOY: 'registry:deploy',
  REGISTRIES_CREATE: 'registries:create',
  REGISTRIES_READ: 'registries:read',
  REGISTRIES_UPDATE: 'registries:update',
  REGISTRIES_DELETE: 'registries:delete',
  WALLET_EXPORT: 'wallet:export',
  WALLET_LINK: 'wallet:link',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ADMIN_PERMISSIONS: Permission[] = [
  PERMISSIONS.PLATFORM_READ, PERMISSIONS.PLATFORM_UPDATE,
  PERMISSIONS.USERS_INVITE, PERMISSIONS.USERS_REMOVE, PERMISSIONS.USERS_LIST,
  PERMISSIONS.ROLES_ASSIGN,
  PERMISSIONS.SCHEMAS_READ, PERMISSIONS.SCHEMAS_WRITE, PERMISSIONS.SCHEMAS_DELETE,
  PERMISSIONS.DOCS_READ, PERMISSIONS.DOCS_WRITE, PERMISSIONS.DOCS_DELETE,
  PERMISSIONS.BLOBS_READ, PERMISSIONS.BLOBS_UPLOAD, PERMISSIONS.BLOBS_DELETE,
  PERMISSIONS.TOKENS_DEPLOY, PERMISSIONS.TOKENS_MINT,
  PERMISSIONS.NFTS_DEPLOY, PERMISSIONS.NFTS_MINT,
  PERMISSIONS.EVENTS_CREATE, PERMISSIONS.EVENTS_MINT,
  PERMISSIONS.REGISTRY_ANCHOR,
  PERMISSIONS.REGISTRIES_READ,
  PERMISSIONS.WALLET_EXPORT, PERMISSIONS.WALLET_LINK,
];

export const MEMBER_PERMISSIONS: Permission[] = [
  PERMISSIONS.SCHEMAS_READ, PERMISSIONS.DOCS_READ,
  PERMISSIONS.BLOBS_READ, PERMISSIONS.BLOBS_UPLOAD,
  PERMISSIONS.USERS_LIST, PERMISSIONS.REGISTRIES_READ,
  PERMISSIONS.WALLET_EXPORT, PERMISSIONS.WALLET_LINK,
];
